# Generated by Django 3.2.3 on 2021-05-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gener',
            new_name='genero',
        ),
    ]
