# Generated by Django 3.2.3 on 2021-06-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('users', '0006_auto_20210602_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
