# Generated by Django 3.2.3 on 2021-06-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210602_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cuenta',
        ),
    ]
